[project]
name = "prism"
version = "0.1.1"
description = "Turn a Raspberry Pi into a reliable HDMI-CEC media player / TV remote."
readme = "README.md"
authors = [{ name = "PauWol", email = "paul22wof@proton.me" }]
requires-python = ">=3.11"
dependencies = [
    "cyclopts>=4.25.2",
    "dotenv>=0.9.9",
    "pythondialog>=3.5.3",
    "typing-extensions>=4.16.0",
    "pyyaml>=6.0.2",
    "pillow>=10.4.0",
    "requests>=2.32.0",
]

[project.scripts]
prism = "prism.cli.main:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
